CREATE TABLE IF NOT EXISTS `todo` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `task` VARCHAR(255) NOT NULL,
    `done` TINYINT(1) NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
